<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260207065545 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE
                "order"
                (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    total_sum DOUBLE PRECISION NOT NULL,
                    status VARCHAR(255) NOT NULL,
                    payment_method VARCHAR(255) NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    user_id INT NOT NULL, PRIMARY KEY (id)
                )
'
        );
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON "order" (user_id)');
        $this->addSql('CREATE INDEX order_status_idx ON "order" (status)');

        $this->addSql(
            'ALTER TABLE "order" ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE  SET NULL'
        );
        $this->addSql('ALTER TABLE cart ALTER user_id DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398A76ED395');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('ALTER TABLE "cart" ALTER user_id SET NOT NULL');
    }
}
