<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260206201035 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql
        (
            'CREATE TABLE
                "cart"
                (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    total DOUBLE PRECISION NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    user_id INT NOT NULL,
                    PRIMARY KEY (id)
                )'
        );

        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA388B7A76ED395 ON "cart" (user_id)');

        $this->addSql
        (
            'CREATE TABLE
                "cart_product"
                (
                    cart_id INT NOT NULL,
                     product_id INT NOT NULL,
                      PRIMARY KEY (cart_id, product_id)
                )'
        );
        $this->addSql('CREATE INDEX IDX_2890CCAA1AD5CDBF ON "cart_product" (cart_id)');

        $this->addSql('CREATE INDEX IDX_2890CCAA4584665A ON "cart_product" (product_id)');

        $this->addSql
        (
            'ALTER TABLE
                "cart"
                ADD CONSTRAINT FK_BA388B7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE'
        );
        $this->addSql
        (
            'ALTER TABLE
                "cart_product"
                ADD CONSTRAINT FK_2890CCAA1AD5CDBF FOREIGN KEY (cart_id) REFERENCES "cart" (id) ON DELETE CASCADE NOT DEFERRABLE'
        );
        $this->addSql
        (
            'ALTER TABLE
                "cart_product"
                ADD CONSTRAINT FK_2890CCAA4584665A FOREIGN KEY (product_id) REFERENCES "product" (id) ON DELETE CASCADE NOT DEFERRABLE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "cart" DROP CONSTRAINT FK_BA388B7A76ED395');
        $this->addSql('ALTER TABLE "cart_product" DROP CONSTRAINT FK_2890CCAA1AD5CDBF');
        $this->addSql('ALTER TABLE "cart_product" DROP CONSTRAINT FK_2890CCAA4584665A');
        $this->addSql('DROP TABLE "cart"');
        $this->addSql('DROP TABLE "cart_product"');
    }
}
